### ISSUE TITLE
Adapt classifier model to backend server

### ISSUE THREAD

**Issue by Byunk** [KAIST-Google-Solution-Challenge/backend#11]
## TODO

- [x] : construct python environment to execute
- [x] : modularize python script (single inference by single request)
- [x] : append to api pipeline
- [x] #12
